# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.3.3
      with:
        arguments: build
  GUI-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Launch GUI
        uses: puredevops/sample-action@v1.3
        with:
          arguments: ./gradlew run --args="--gui assets/dna/random/dnalong.fa"
        # Whether caching wrapper installation is enabled or not, default to 'true'
        # wrapper-cache-enabled: # optional
        # Whether caching dependencies is enabled or not, default to 'false'
        # dependencies-cache-enabled: # optional
        # Globs of files to hash in the build root directory, separated by new lines, use best-effort if unset
        # dependencies-cache-key: # optional
        # Whether to restore only if exact match, default to 'false'
        # dependencies-cache-exact: # optional
        # Whether caching build configuration is enabled or not, default to 'false'
        # configuration-cache-enabled: # optional
        # Globs of files to hash in the build root directory, separated by new lines, use best-effort if unset
        # configuration-cache-key: # optional
        # Whether to restore only if exact match, default to 'false'
        # configuration-cache-exact: # optional
